Fix/1435 settings in full screen mode
KhalisFoundation/sttm-web pull request #1443
Opened 2021-05-19 06:54 UTC by navdeepsingh

@plug-n-play please review.
Staging Link: https://sttm-dev-fix-1435-setti-hhkooz.herokuapp.com/

* [x]  Passed [sanity tests](http://bit.ly/sttm-sanity-tests).
* [x]  Ran `npm test` & fixed newly introduced lint errors.
* [x]  Checked console for errors.

<!-- New to markdown? Simply put an 'x' between [ ] to check it. Like [x] this. (No spaces).

2021-05-19 18:28 UTC, plug-n-play commented on src/js/components/ShareButtons.js
> +        <div id="fullscreen-share-menu">
Why has this been made part of ShareButtons component? It doesn't seem to belong here.

2021-05-19 18:29 UTC, plug-n-play commented on src/scss/_sharing.scss
> +#fullscreen-share-menu {
Same for other things. This is not the right place to add this component and related styling.

2021-05-19 18:30 UTC, plug-n-play requested changes
Either use an existing appropriate component for this change. If it doesn't exists, please create a new one.

2021-05-21 06:37 UTC, saintsoldierx commented
@plug-n-play please review today if you can. Thanks

2021-05-21 18:22 UTC, plug-n-play approved these changes

2021-05-21 18:25 UTC, plug-n-play commented
Thank you @navdeepsingh

Good job!

2021-05-22 06:23 UTC, merged

2021-05-22 07:17 UTC, navdeepsingh commented
> Thank you @navdeepsingh
> 
> Good job!

Thanks @plug-n-play for the compliment. It matters to me a lot.