Fixes MahaanKoshTooltip Reading mode bug: #1741 + Prettier formatting
KhalisFoundation/sttm-web pull request #1742
Opened 2024-09-26 00:14 UTC by JapnitS

* [x]  Passed [sanity tests](http://bit.ly/sttm-sanity-tests).
* [x]  Ran `npm test` & fixed newly introduced lint errors.
* [x]  Checked console for errors.

Fixes bug #1741 by wrapping `BaaniLine` in `MahaanKoshContext.provider`.
+ Main logic diff [pointer](https://github.com/KhalisFoundation/sttm-web/compare/dev...JapnitS:sttm-web:Bugfix-MahaanKoshTooltipReadingMode#diff-e317174e052c1908e085efa0da22d1ed1fb5a32fc7f89246c30d0487c48c9cc7R888-R916)

+ Test snapshot change
+ Prettier formatting
<!-- New to markdown? Simply put an 'x' between [ ] to check it. Like [x] this. (No spaces).

2024-09-26 06:11 UTC, gurjit03 commented
> * [x]   Passed [sanity tests](http://bit.ly/sttm-sanity-tests).
> * [x]   Ran `npm test` & fixed newly introduced lint errors.
> * [x]   Checked console for errors.
> 
> Fixes bug #1741 by wrapping `BaaniLine` in `MahaanKoshContext.provider`.
> 
> * Main logic diff [pointer](https://github.com/KhalisFoundation/sttm-web/compare/dev...JapnitS:sttm-web:Bugfix-MahaanKoshTooltipReadingMode#diff-e317174e052c1908e085efa0da22d1ed1fb5a32fc7f89246c30d0487c48c9cc7R888-R916)
> * Test snapshot change
> * Prettier formatting

@JapnitS Great work 🔥  fixing this bug. Can we kindly remove this prettier formatting as we mostly relying on the VScode internal formatter so that we have similar formatting across the product.

Rather I would propose to create another ticket to move the formatting to the prettier and we can do so in 1 formatting PR.
cc @Gauravjeetsingh

2024-09-26 06:17 UTC, gurjit03 requested changes

2024-09-26 06:17 UTC, gurjit03 commented on src/js/components/Baani/Baani.js
> -                      key={source}
@JapnitS here we are fixing the key to the spanish language

2024-09-26 06:17 UTC, gurjit03 commented on src/js/components/Baani/Baani.js
> +              <div
@JapnitS Lets create a small component named DisplayMixedViewBaani and use that here.

2024-09-27 20:31 UTC, JapnitS commented
Closed in favor of https://github.com/KhalisFoundation/sttm-web/pull/1743

2024-09-27 20:31 UTC, closed without merging